[project]
name = "research-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.10.0",
    "langchain>=1.2.8",
    "langchain-anthropic>=1.3.1",
    "langgraph>=1.0.7",
    "python-dotenv>=1.2.1",
]
